# Site settings
title: Biocompute Lab
email: thomas.gorochowski@bristol.ac.uk
description: "Biology computes... let's figure out how."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.biocomputelab.org" # the base hostname & protocol for your site

collections:
  team:
    output: true
    permalink: /team/:path/

twitter_username:
github_username:

# Build settings
markdown: kramdown

# How many articles do you wish to appear on the front page:
paginate: 10
paginate_path: "/news/page:num/"

#theme: jekyll-theme-cayman